version: "3"
services:
  api-gateway-container:
    image: selimhorri/api-gateway-ecommerce-boot:0.1.0
    ports:
      - "8080:8080"
    networks:
      - microservices_network
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296/
      - SPRING_ZIPKIN_BASE_URL=http://zipkin-container:9411
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery-container:8761/eureka/
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - EUREKA_INSTANCE_HOSTNAME=api-gateway-container
      - SPRING_CLOUD_GATEWAY_DISCOVERY_LOCATOR_ENABLED=true
      - SPRING_CLOUD_GATEWAY_DISCOVERY_LOCATOR_LOWER_CASE_SERVICE_ID=true
      - SPRING_SLEUTH_SAMPLER_PROBABILITY=1
    depends_on:
      - service-discovery-container
      - cloud-config-container
      - zipkin-container

  proxy-client-container:
    image: selimhorri/proxy-client-ecommerce-boot:0.1.0
    ports:
      - "8900:8900"
    networks:
      - microservices_network
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296/
      - SPRING_ZIPKIN_BASE_URL=http://zipkin-container:9411
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery-container:8761/eureka/
      - EUREKA_CLIENT_ENABLED=true
      - EUREKA_CLIENT_FETCH_REGISTRY=true
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - EUREKA_INSTANCE_HOSTNAME=proxy-client-container
      - RIBBON_EUREKA_ENABLED=true
      - SPRING_SLEUTH_SAMPLER_PROBABILITY=1
    depends_on:
      - service-discovery-container
      - cloud-config-container

  order-service-container:
    image: selimhorri/order-service-ecommerce-boot:0.1.0
    ports:
      - "8300:8300"
    networks:
      - microservices_network
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296/
      - SPRING_ZIPKIN_BASE_URL=http://zipkin-container:9411
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery-container:8761/eureka/
      - EUREKA_CLIENT_ENABLED=true
      - EUREKA_CLIENT_FETCH_REGISTRY=true
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - EUREKA_INSTANCE_HOSTNAME=order-service-container
      - RIBBON_EUREKA_ENABLED=true
      - SPRING_SLEUTH_SAMPLER_PROBABILITY=1
    depends_on:
      - service-discovery-container
      - cloud-config-container

  payment-service-container:
    image: selimhorri/payment-service-ecommerce-boot:0.1.0
    ports:
      - "8400:8400"
    networks:
      - microservices_network
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296/
      - SPRING_ZIPKIN_BASE_URL=http://zipkin-container:9411
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery-container:8761/eureka/
      - EUREKA_CLIENT_ENABLED=true
      - EUREKA_CLIENT_FETCH_REGISTRY=true
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - EUREKA_INSTANCE_HOSTNAME=payment-service-container
      - RIBBON_EUREKA_ENABLED=true
      - SPRING_SLEUTH_SAMPLER_PROBABILITY=1
    depends_on:
      - service-discovery-container
      - cloud-config-container

  product-service-container:
    image: selimhorri/product-service-ecommerce-boot:0.1.0
    ports:
      - "8500:8500"
    networks:
      - microservices_network
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296/
      - SPRING_ZIPKIN_BASE_URL=http://zipkin-container:9411
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery-container:8761/eureka/
      - EUREKA_CLIENT_ENABLED=true
      - EUREKA_CLIENT_FETCH_REGISTRY=true
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - EUREKA_INSTANCE_HOSTNAME=product-service-container
      - RIBBON_EUREKA_ENABLED=true
      - SPRING_SLEUTH_SAMPLER_PROBABILITY=1
    depends_on:
      - service-discovery-container
      - cloud-config-container

  shipping-service-container:
    image: selimhorri/shipping-service-ecommerce-boot:0.1.0
    ports:
      - "8600:8600"
    networks:
      - microservices_network
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296/
      - SPRING_ZIPKIN_BASE_URL=http://zipkin-container:9411
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery-container:8761/eureka/
      - EUREKA_CLIENT_ENABLED=true
      - EUREKA_CLIENT_FETCH_REGISTRY=true
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - EUREKA_INSTANCE_HOSTNAME=shipping-service-container
      - RIBBON_EUREKA_ENABLED=true
      - SPRING_SLEUTH_SAMPLER_PROBABILITY=1
    depends_on:
      - service-discovery-container
      - cloud-config-container

  user-service-container:
    image: selimhorri/user-service-ecommerce-boot:0.1.0
    ports:
      - "8700:8700"
    networks:
      - microservices_network
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296/
      - SPRING_ZIPKIN_BASE_URL=http://zipkin-container:9411
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery-container:8761/eureka/
      - EUREKA_CLIENT_ENABLED=true
      - EUREKA_CLIENT_FETCH_REGISTRY=true
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - EUREKA_INSTANCE_HOSTNAME=user-service-container
      - RIBBON_EUREKA_ENABLED=true
      - SPRING_SLEUTH_SAMPLER_PROBABILITY=1
    depends_on:
      - service-discovery-container
      - cloud-config-container

  favourite-service-container:
    image: selimhorri/favourite-service-ecommerce-boot:0.1.0
    ports:
      - "8800:8800"
    networks:
      - microservices_network
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296/
      - SPRING_ZIPKIN_BASE_URL=http://zipkin-container:9411
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery-container:8761/eureka/
      - EUREKA_CLIENT_ENABLED=true
      - EUREKA_CLIENT_FETCH_REGISTRY=true
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - EUREKA_INSTANCE_HOSTNAME=favourite-service-container
      - RIBBON_EUREKA_ENABLED=true
      - SPRING_SLEUTH_SAMPLER_PROBABILITY=1
    depends_on:
      - service-discovery-container
      - cloud-config-container
