apiVersion: apps/v1
kind: Deployment
metadata:
  name: favourite-service
  namespace: ecommerce-microservices
  labels:
    app: favourite-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: favourite-service
  template:
    metadata:
      labels:
        app: favourite-service
    spec:
      containers:
      - name: favourite-service
        image: ecommerce-favourite-service:dev
        imagePullPolicy: Never
        ports:
        - containerPort: 8500
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "dev"
        - name: SPRING_ZIPKIN_BASE_URL
          value: "http://zipkin-service:9411"
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://service-discovery-service:8761/eureka/"
        - name: SPRING_CONFIG_IMPORT
          value: "optional:configserver:http://cloud-config-service:9296/"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:h2:mem:favouritedb"
        - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
          value: "org.h2.Driver"
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: "create-drop"
        resources:
          requests:
            memory: "1Gi"
            cpu: "300m"
          limits:
            memory: "2Gi"
            cpu: "700m"
        startupProbe:
          httpGet:
            path: /favourite-service/actuator/health
            port: 8500
          initialDelaySeconds: 20
          periodSeconds: 10
          failureThreshold: 30
        livenessProbe:
          httpGet:
            path: /favourite-service/actuator/health
            port: 8500
          initialDelaySeconds: 180
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /favourite-service/actuator/health
            port: 8500
          initialDelaySeconds: 180
          periodSeconds: 5
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: favourite-service-service
  namespace: ecommerce-microservices
  labels:
    app: favourite-service
spec:
  selector:
    app: favourite-service
  ports:
  - port: 8500
    targetPort: 8500
    protocol: TCP
  type: ClusterIP
